name: COMPOSITE_ACTION 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      run_type:
        description: "Run type: regular or nightly"
        default: "regular"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # starts  self-hosted runner in Clouds (AWS and AZURE suported for now). Cleanup in the stop-runner.
  test-subworkflow:
    uses: ./.github/workflows/get-artifact.yaml
    name: "calling sub-workflow"
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

  another-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - run: |
          set -x
          ls .
          ls .github
          ls .github/workflows/
